apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
  namespace: nginx
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/" 
